feat: add herma 4346 labels
entropia/paperless-asn-qr-codes pull request #12
Opened 2024-01-06 10:13 UTC by markussiebert

Hi, 
I added the herma 4346 labels. They print okay - everything is on the label. The first row prints at the bottom of the label, the last row at the very top. But I think it's a general issue - as the measurements are very precise.

Thank you for your great work

2024-01-06 19:12 UTC, margau approved these changes

2024-01-17 19:35 UTC, markussiebert commented
The issues I had were 97% scaling on iOS - this works perfect

2024-01-21 18:36 UTC, margau commented
This looks good to me. We might also wanna add this to the README?

2024-04-09 10:35 UTC, markussiebert commented
Just lgtm

2024-04-17 19:23 UTC, margau requested changes
If this is tested and working, can we add this to the "known good" labels in https://github.com/entropia/paperless-asn-qr-codes#supported-sheets ?

Thanks!

2024-11-03 10:33 UTC, markussiebert commented
> If this is tested and working, can we add this to the "known good" labels in https://github.com/entropia/paperless-asn-qr-codes#supported-sheets ?
> 
> Thanks!

fixed

2025-01-26 19:23 UTC, promasu commented on README.md
> +  --format, -f {averyL4731,averyL4732,avery5160,avery5161,avery5163,avery5167,avery5371,herma4201,herma10003,herma4346}
The `--format, -f` breaks with the format of the rest of the file. Maybe consider a dedicated PR with the format change.

And what have the averyL4732 and herma4201 to do with this PR?

2025-01-26 19:28 UTC, margau commented on README.md
> +  --format, -f {averyL4731,averyL4732,avery5160,avery5161,avery5163,avery5167,avery5371,herma4201,herma10003,herma4346}
Yes, thats something weird with the history. Will adjust that.

2025-01-26 19:37 UTC, promasu approved these changes
Looks better now.

2025-01-26 19:41 UTC, merged